# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwApp', '0003_auto_20171221_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pic',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='hw/'),
        ),
    ]
